import Head from "next/head";

import { Inter } from "next/font/google";
import Drawing from "./drawing";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ drawings }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mt-10">
        <div className="grid grid-cols-3 gap-5">
          {drawings?.map((drawing) => (
            <Drawing key={drawing.id} drawing={drawing}></Drawing>
          ))}
        </div>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const res = await fetch("https://www.planndesign.com/gapi/drawings");
  const data = await res.json();

  return {
    props: {
      drawings: data,
    },
  };
}
